
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:https://github.com/yadavsudhir405/config.git
          #basedir:${HOME}/Desktop/config ---->To target to local git repository
server:
  port: 8888
