
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Desktop/config
          #basedir:${HOME}/Desktop/config ---->To target to local git repository
server:
  port: 8888
